# Makefile for algos

CC = gcc
CFLAGS = -g -Wall
FILES = 100 10137

all: $(FILES)

100: 100.c
	$(CC) $(CFLAGS) -o 100 100.c

10137: 10137.c
	$(CC) $(CFLAGS) -o 10137 10137.c

clean:
	rm -f $(FILES) *~ *.o
